### PR TITLE
[Enhancement] Support for HipChat api v2

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
This works with hipchat api v2. I use it in one of my apps, so battle tested :smile:  Let me know if this requires any changes to get it merged back to yours.

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@surma anything else required to merge this PR?

**Comment by dtl** [comment]
@sivakumar-kailasam thanks for the PR and sorry for the delay. I'll check the changes over the day.

**Comment by dtl** [comment]
:+1:

**Comment by sivakumar-kailasam** [comment]
Glad I could help 😄

**Comment by dtl** [comment]
ty @sivakumar-kailasam :smiley:

**Pull request merged**
